version: '1'
services:
  nginx:
    environment:
      NGINX_PORT: 80
    build: ./config/nginx/
    ports:
      - "8080:80"
    links:
      - "api_1:api1"
      - "api_2:api2"
    depends_on:
      - api_1
      - api_2
  api_1:
    environment:
        API_PORT: 8000
    build:
      context: .
  api_2:
    environment:
      API_PORT: 8001
    build:
      context: .
  db:
    build: ./db/
    restart: always
    environment:
      POSTGRES_USER: "pet_admin"
      POSTGRES_PASSWORD: "example"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      LANG: "pt_BR.utf8"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --locale-provider=icu --icu-locale=pt-BR"
      TZ: 'Brazil/East'
      PGTZ: 'Brazil/East'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pet_admin"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5050:5432"
    volumes:
      - "./db/setup:/docker-entrypoint-initdb.d"
